Feature/skill query models
UCBX-2024-Team-Wombat/Skill-Share-Hub pull request #10
Opened 2024-12-06 05:02 UTC by bwolkoys

2024-12-06 20:44 UTC, jvalliswalker requested changes
Hi @bwolkoys. Thanks for your work here! I have a number of requested changes in the form of comments. Some of them are minor changes, and some of them are for catching errors/bugs I ran into during testing. 

One thing I wanted to reiterate is the importance of testing your code before moving on to a PR. There are a number of ways to do this, and we can go over some together if you'd like. However it gets done, you need to make sure the code works as desired before handing it off. This means spinning up the server and walking through each use case for the code your writing. With this pull specifically, you need to test each query and mutation after writing it, and check for edge cases. I did this for this PR via the graphql sandbox endpoint since we don't have a UI for testing these queries yet.

2024-12-06 20:44 UTC, jvalliswalker commented on server/schemas/typeDefs.js
> +    modifySkill(id: ID!, name: String!, description: String!): Skill
Can you make the "name" and "description" not required here? Otherwise if I want to modify a skill's name but not its description, I still have to enter in the same description it had before since description is required. The reverse is true with name.

2024-12-06 20:44 UTC, jvalliswalker commented on server/schemas/typeDefs.js
> +    addSkill(name: String!, description: String!): Skill
Can you make "description" not required here?

2024-12-06 20:44 UTC, jvalliswalker commented on server/schemas/resolvers.js
> +      return await SkillRelationship.find({}).populate('skill').populate('user');
Here you have a query that will return all skill relationships, but in practice we'll be wanting to pull skill relationships by the user they belong to. Otherwise a user trying to view their own skill list (via their skill relationships) will see the skill relationships for every user in the database. Let me know if that makes sense.

Please update to run a "find" based on passed User Id.

2024-12-06 20:44 UTC, jvalliswalker commented on server/schemas/resolvers.js
> +    getSkillRelationships: async (parent, args, context) => {
I tried running this in the graphql sandbox and got a server error stating "Cannot read properties of undefined (reading 'find')". I did some sleuthing and it looks like the SkillRelationship model is exported in the `Skill_Relationship.js` file, but not imported and re-exported in the `index.js` file in the same folder. Because of this the import of SkillRelationship on line 1 of this file didn't resolve, causing this error. 

You'll need to make that import/export in the `index.js` file to resolve this.

2024-12-06 20:44 UTC, jvalliswalker commented on server/schemas/typeDefs.js
> +    yearsOfExperience: Int
So I spent like an hour trying to get decimals to work, but it turns out in graphql/mongodb it's a real pain. Instead of Int, can you change this (and all corresponding schema entries) to String? We can store a decimal as a string and just convert it from Decimal to String on the front end when a user submits data.

2024-12-06 20:44 UTC, jvalliswalker commented on server/schemas/typeDefs.js
> +    addSkillRelationship(skill: ID!, yearsOfExperience: Int!, areasOfExpertise: String!): SkillRelationship
For this mutation, we need to have a User Id as a required parameter. Otherwise we  end up with a Skill Relationship record that relates to a skill but not a user. 

Two other small things: 
1. Can you make areasOfExpertise not required?
2. See earlier comment for changing "yearsOfExperience" to a string

2024-12-06 20:44 UTC, jvalliswalker commented on server/schemas/typeDefs.js
> +    getSkillRelationships: [SkillRelationship]
Mentioned in resolvers too, but please add user Id as a required parameter for getSkillRelationships

2024-12-08 22:25 UTC, bwolkoys commented on server/schemas/typeDefs.js
> +    modifySkill(id: ID!, name: String!, description: String!): Skill
this comment had been updated in feature/profile-page

2024-12-08 22:26 UTC, bwolkoys commented on server/schemas/typeDefs.js
> +    addSkill(name: String!, description: String!): Skill
this comment had been updated in feature/profile-page

2024-12-08 22:27 UTC, bwolkoys commented on server/schemas/resolvers.js
> +      return await SkillRelationship.find({}).populate('skill').populate('user');
this comment had been updated in feature/profile-page

2024-12-08 22:27 UTC, bwolkoys commented on server/schemas/resolvers.js
> +    getSkillRelationships: async (parent, args, context) => {
this comment had been updated in feature/profile-page

2024-12-08 22:28 UTC, bwolkoys commented on server/schemas/typeDefs.js
> +    yearsOfExperience: Int
this comment had been updated in feature/profile-page

2024-12-08 22:29 UTC, bwolkoys commented on server/schemas/typeDefs.js
> +    addSkillRelationship(skill: ID!, yearsOfExperience: Int!, areasOfExpertise: String!): SkillRelationship
this comment had been updated in feature/profile-page

2024-12-08 22:29 UTC, bwolkoys commented on server/schemas/typeDefs.js
> +    getSkillRelationships: [SkillRelationship]
this comment had been updated in feature/profile-page

2024-12-09 20:14 UTC, closed without merging

2024-12-09 20:15 UTC, jvalliswalker commented
Closed per transition to PR https://github.com/UCBX-2024-Team-Wombat/Final-Project/pull/12