Feature/profile page
UCBX-2024-Team-Wombat/Skill-Share-Hub pull request #12
Opened 2024-12-06 21:16 UTC by bwolkoys

2024-12-06 23:39 UTC, jvalliswalker requested changes
Hey @bwolkoys. Thanks for making the updates from the prior PR. 

In the future, instead of wrapping those changes into another feature branch (e.g. this one), please make the changes in the original branch. The reason for this is that now the "skill query model" and "profile page" branches are conflated, so we've lost the isolation/distinction for each. It also means that all the comments I made in the prior PR aren't a part of this PR, so I have to look between the two as I read through this request to check to see if all the items were addressed. When you're working in a company with a larger code base and a number of different developers this can lead to big headaches/merge conflicts/etc.

Adding to my comment in the last PR about testing, I want to suggest that you practice going a bit slower in your development process. You're often turning around code changes very quickly, but I think that speed is part of the reason you're missing some items and testing.

There are a few things to update in this PR. Please leave a comment for each of my inline comments indicating that they're resolved so I can do another read through once you update the PR.

2024-12-06 23:39 UTC, jvalliswalker commented on server/schemas/typeDefs.js
> +    getSkillRelationshipsByUserId: [SkillRelationship]
I see you added a new query, but it doesn't have the user Id as a parameter for the query. Instead of having this separate query, remove line 33 and update line 32 to read `getSkillRelationships(userId: ID!): [SkillRelationship]`. You'll also need to update the corresponding resolver in `resolvers.js` and query in `queries.js`

2024-12-06 23:39 UTC, jvalliswalker commented on server/schemas/resolvers.js
> +    modifySkill: async (parent, { id, name, description}) => {
I tried making a modification in the graphql sandbox but get the error below when I run it. Please investigate and resolve.

![image](https://github.com/user-attachments/assets/cd8431d7-5fd4-4ee4-93c2-834a6ca8bce7)

2024-12-06 23:39 UTC, jvalliswalker commented on client/src/components/ProfileSkills/ProfileSkills.jsx
I like your thinking ahead with this component, but I think we'd need to strategize a bit more with how we'd like this to work before we add it to the code base. Since this is a little out of scope for the original task, I'd ask you what you'd prefer: Do you want to pull this component from this PR, or get some additional requirements for it and continue developing it?

2024-12-08 21:31 UTC, bwolkoys commented on server/schemas/typeDefs.js
> +    getSkillRelationshipsByUserId: [SkillRelationship]
This has been updated in the code. Updated i  typeDefs, resolvers and queries.js. Question- for line 70 inside resolvers file on the server side. Do I need to change user to userId as well?

2024-12-08 21:32 UTC, bwolkoys commented on server/schemas/resolvers.js
> +    modifySkill: async (parent, { id, name, description}) => {
Have a tutor session tomorrow to continue to  work on this.

2024-12-08 21:49 UTC, bwolkoys commented on client/src/components/ProfileSkills/ProfileSkills.jsx
I'm going to get additional information and see if there is an easier way to do this.

2024-12-08 22:22 UTC, jvalliswalker commented on server/schemas/typeDefs.js
> +    getSkillRelationshipsByUserId: [SkillRelationship]
Thanks @bwolkoys! For the line 70 question, it's not required, but I would recommending changing it from `user` to `userId` for clarify/readability.

2024-12-09 00:53 UTC, jvalliswalker requested changes
Thanks for all your hard work on this @bwolkoys. Per our meeting today, most of these items are resolved. There are two minor things I found that need a final resolution.

First, the `addSkill` mutation in `typeDefs.js` doesn't require `yearsOfExperience`, but in the `Skill_Relationships.js` model that field is required. I found this when I tried to run the `addSkill` mutation without `yearsOfExperience` entered and ran into an error. This is probably an oversite on my part, but I'll offer the solution to you. Can you either make `yearsOfExperience` required in the `addSkill` mutation in `typeDefs.js`, or make that field not required in the `Skill_Relationship.js` model?

Second is that I ran `npm pull origin integration` while checked out on your branch and it came back with a change. The change is a "merge conflict," which has to do with the fact that I removed the fields in the SkillRelationship type in `typeDefs.js` because they didn't exist yet and it was throwing query errors for other testing I was doing. Can you run a pull from integration and resolve the merge conflict? In this case you can just click "accept current" in the merge editor. Then just re-push the changes.

![image](https://github.com/user-attachments/assets/2bfb7053-5388-4acb-a55b-e6dcc9e75263)

![image](https://github.com/user-attachments/assets/3fa9a1cd-2507-442c-ad66-2ae60176c568)

![image](https://github.com/user-attachments/assets/38d70fde-7544-41eb-86d3-4a5558930095)

2024-12-09 02:50 UTC, bwolkoys commented
I'm getting this problem again when I try "git pull origin integration" - If I do a rebase, will the conflicts show up and then I can manually accept them?
<img width="786" alt="Screenshot 2024-12-08 at 6 49 37 PM" src="https://github.com/user-attachments/assets/16e310f7-c8e3-4ab4-8613-647ef2a61840">

2024-12-09 20:16 UTC, merged